### ISSUE TITLE
TODO: New features

### ISSUE THREAD

**Issue by daphnei** [kirubarajan/roft#6]
This issue contains a list of features we would like to implement.

- [x] Allow descriptions of methods to be uploaded to database from a json file.
- [ ] Finish adding content to tutorial page.
- [ ] Add option to play rounds without logging in.
- [x] Create a static URL for each generation example.
- [x] HTML for Amazon Mechanical Turk task
- [x] "X remaining" at top is buggy and goes into negative numbers.

**Comment by daphnei** [comment]
Closing this issue as we havemoved to individual issues for each bug.
