### ISSUE TITLE
TODO: Bugs

### ISSUE THREAD

**Issue by daphnei** [kirubarajan/roft#7]
This issue tracks the minor bugs that should be fixed before release:

- [x] If user logs out in a different tab and then tries to play a round they get a 500 error.
- [x] Counts of “number available” don’t go down as user does annotations.
- [x] I think the number of points awards for guessing too late is 1 lower than it should be.
- [x] From Chris: When it's entire human-written and user correct guesses this, no points are awarded and the notification message is incorrect.

**Comment by kirubarajan** [comment]
These issues are all included in other issues, so I'm closing this.
